name: research-paper-assistant

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend:3001
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
        - VITE_GROQ_API_KEY=${VITE_GROQ_API_KEY}
        - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
        - VITE_BASE_URL=${VITE_BASE_URL}
        - VITE_MODEL=${VITE_MODEL}
        - VITE_GROQ_MODEL=${VITE_GROQ_MODEL}
        - VITE_PINECONE_API_KEY=${VITE_PINECONE_API_KEY}
        - VITE_PINECONE_ENVIRONMENT=${VITE_PINECONE_ENVIRONMENT}
        - VITE_PINECONE_INDEX_NAME=${VITE_PINECONE_INDEX_NAME}
        - VITE_PINECONE_HOST=${VITE_PINECONE_HOST}
        - VITE_PINECONE_DIMENSIONS=${VITE_PINECONE_DIMENSIONS}
        - VITE_PINECONE_METRIC=${VITE_PINECONE_METRIC}
        - VITE_EMBEDDING_MODEL=${VITE_EMBEDDING_MODEL}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
        - FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - GROQ_API_KEY=${VITE_GROQ_API_KEY}
        - BASE_URL=${VITE_BASE_URL}
        - MODEL=${VITE_MODEL}
        - GROQ_MODEL=${VITE_GROQ_MODEL}
        - PINECONE_API_KEY=${VITE_PINECONE_API_KEY}
        - PINECONE_ENVIRONMENT=${VITE_PINECONE_ENVIRONMENT}
        - PINECONE_INDEX_NAME=${VITE_PINECONE_INDEX_NAME}
        - PINECONE_HOST=${VITE_PINECONE_HOST}
        - PINECONE_DIMENSIONS=${VITE_PINECONE_DIMENSIONS}
        - PINECONE_METRIC=${VITE_PINECONE_METRIC}
        - EMBEDDING_MODEL=${VITE_EMBEDDING_MODEL}
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./backend
        target: /app
        consistency: delegated
      - type: volume
        source: backend_node_modules
        target: /app/node_modules
    restart: unless-stopped
    environment:
      - NODE_ENV=development

volumes:
  backend_node_modules: {}
